### ISSUE TITLE
Upgrade to 1.10.6

### ISSUE THREAD

**Issue by cmharlow** [tulibraries/ansible-role-airflow#27]

**Comment by schmitmd** [comment]
Related to this, the "num_runs" option in defaults/main.yml specifies "0" as the value, which doesn't make any sense according to the official documentation.  https://airflow.apache.org/docs/stable/configurations-ref.html?highlight=num_runs#num-runs

**Comment by cmharlow** [comment]
lol yeah, thanks for that catch @schmitmd - looks like a bit of copypasta from the original role. i don't work at this place any longer, but good to note this!
